const levels = [
  {
    number: 1,
    bibleVerse: `But, “Let the one who boasts boast in the Lord.”[a] 18 For it is not the one who commends himself who is approved, but the one whom the Lord commends.`,
    verse: `2 Corinthians 10:17-18 (NIV)`,
    questions: [
      {
        q: `Who wrote the letter to the Corinthians?`,
        one: `Jesus`,
        two: `Matthew`,
        three: `John`,
        four: `Paul`,
        right: "four",
        read: false,
        status: false,
      },
      {
        q: `What was another name of the Apostle Paul?`,
        one: `Saul of Tarsus`,
        two: `Simon`,
        three: `Abraham`,
        four: `Israel`,
        right: "one",
        read: false,
        status: false,
      },
      {
        q: `Where is the text located?`,
        one: `Psalms`,
        two: `2 Corinthians`,
        three: `Juan`,
        four: `1 Corinthians`,
        right: "two",
        read: false,
        status: false,
      },
    ],
  },
  {
    number: 2,
    bibleVerse: `Whoever has the Son has life; whoever does not have the Son of God does not have life.`,
    verse: `1 John 5:12 (NIV)`,
    questions: [
      {
        q: `Who wrote the book of John?`,
        one: `Juan`,
        two: `Matthew`,
        three: `Judas`,
        four: `Paul`,
        right: "one",
        read: false,
        status: false,
      },
      {
        q: `¿Question number two?`,
        one: `b1`,
        two: `b2`,
        three: `b3`,
        four: `b4`,
        right: "three",
        read: false,
        status: false,
      },
      {
        q: `¿Question number four?`,
        one: `c1`,
        two: `c2`,
        three: `c3`,
        four: `c4`,
        right: "two",
        read: false,
        status: false,
      },
    ],
  },
];
